# Generated by Django 5.0.7 on 2024-07-19 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0002_alter_match_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableplayer',
            name='elo',
        ),
        migrations.AddField(
            model_name='availableplayer',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='availableplayer',
            name='last_updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='last_updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
