# Generated by Django 5.0.7 on 2024-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0004_tournament_match_draw_tournamentparticipant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentmatch',
            old_name='tournament_round',
            new_name='round',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='score',
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
