# Generated by Django 5.0.7 on 2024-07-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0005_rename_tournament_round_tournamentmatch_round_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='last_updated_time',
        ),
        migrations.AddField(
            model_name='match',
            name='rating_change_loser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='rating_change_winner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='rating_change_loser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='rating_change_winner',
            field=models.IntegerField(default=0),
        ),
    ]
